services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - './run/pgsql:/var/lib/postgresql/data:rw'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
