"""add twitch id

Revision ID: f078bf41b8a3
Revises: df0fe943d658
Create Date: 2023-05-01 02:46:20.396131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f078bf41b8a3'
down_revision = 'df0fe943d658'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitch_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_twitch_id'), 'users', ['twitch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_twitch_id'), table_name='users')
    op.drop_column('users', 'twitch_id')
    # ### end Alembic commands ###
