"""initial

Revision ID: df0fe943d658
Revises: 
Create Date: 2023-05-01 02:40:38.626783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0fe943d658'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_date'), 'users', ['date'], unique=False)
    op.create_index(op.f('ix_users_display_name'), 'users', ['display_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('point_value',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('user', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_value_channel_name'), 'point_value', ['channel_name'], unique=False)
    op.create_index(op.f('ix_point_value_date'), 'point_value', ['date'], unique=False)
    op.create_index(op.f('ix_point_value_id'), 'point_value', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_value_id'), table_name='point_value')
    op.drop_index(op.f('ix_point_value_date'), table_name='point_value')
    op.drop_index(op.f('ix_point_value_channel_name'), table_name='point_value')
    op.drop_table('point_value')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_display_name'), table_name='users')
    op.drop_index(op.f('ix_users_date'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
