"""remove index

Revision ID: db8c1d865a90
Revises: f078bf41b8a3
Create Date: 2023-05-01 12:22:04.396826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8c1d865a90'
down_revision = 'f078bf41b8a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_display_name', table_name='users')
    op.drop_index('ix_users_twitch_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_twitch_id', 'users', ['twitch_id'], unique=False)
    op.create_index('ix_users_display_name', 'users', ['display_name'], unique=False)
    # ### end Alembic commands ###
