"""add token

Revision ID: 94efa8093307
Revises: db8c1d865a90
Create Date: 2023-05-01 12:33:07.426384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94efa8093307'
down_revision = 'db8c1d865a90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
