"""init

Revision ID: 237b5564e401
Revises: 
Create Date: 2023-05-07 12:20:28.903326

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '237b5564e401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('twitch_id', sa.String(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('token', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_date'), 'users', ['date'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=False)
    op.create_table('point_value',
                    sa.Column('id', sa.Uuid(), nullable=False),
                    sa.Column('channel_name', sa.String(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('user', sa.Uuid(), nullable=False),
                    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_point_value_channel_name'), 'point_value', ['channel_name'], unique=False)
    op.create_index(op.f('ix_point_value_date'), 'point_value', ['date'], unique=False)
    op.create_index(op.f('ix_point_value_id'), 'point_value', ['id'], unique=False)
    op.create_index('user_point_value_channel_date', 'point_value', ['user', 'date', 'channel_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_point_value_channel_date', table_name='point_value')
    op.drop_index(op.f('ix_point_value_id'), table_name='point_value')
    op.drop_index(op.f('ix_point_value_date'), table_name='point_value')
    op.drop_index(op.f('ix_point_value_channel_name'), table_name='point_value')
    op.drop_table('point_value')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_date'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
