"""add index

Revision ID: d0af3fd39346
Revises: 94efa8093307
Create Date: 2023-05-01 21:05:01.217206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0af3fd39346'
down_revision = '94efa8093307'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('user_point_value_channel_date', 'point_value', ['user', 'date', 'channel_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('user_point_value_channel_date', table_name='point_value')
    # ### end Alembic commands ###
