"""initial migration

Revision ID: a5e1d4e1dbeb
Revises: 
Create Date: 2023-04-30 23:06:49.093885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e1d4e1dbeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('point_value',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_point_value_channel_name'), 'point_value', ['channel_name'], unique=False)
    op.create_index(op.f('ix_point_value_id'), 'point_value', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_point_value_id'), table_name='point_value')
    op.drop_index(op.f('ix_point_value_channel_name'), table_name='point_value')
    op.drop_table('point_value')
    # ### end Alembic commands ###
